### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by sreckojoksimovic** [TeamCohen/MinorThird#2]
Hi,
looks like I like this Issue feature :) I have few, more concrete questions (at least I think so...).

Firstly, I would like to create a set of methods which are going to be used for feature extraction. I need to test different approaches (unigrams, bigrams, POS-bigrams, etc.).

Secondly, I was thinking of using Mixup language in the same process.

Could you please tell me what would be the best place to start?

The idea is to use extracted features to build a machine learning model. But, one at the time… :)

Srecko

**Comment by linfrank** [comment]
Take a look at MyFE.java in the demo directory for a good example of a feature extractor:

https://github.com/TeamCohen/MinorThird/blob/master/demos/MyFE.java

If you want to use Mixup you can follow the Mixup tutorial on the wiki.

**Comment by sreckojoksimovic** [comment]
Thanks.
I forgot for this one...
